version: 2  # Version of CircleCI
jobs:
  build:
    docker:
      - image: node:18.12.0-alpine3.16
    steps:
      - run:
          name: Install Docker client
          command: |
            apk update && apk install -y curl
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: docker build -t dynkine/docker-express-app .

      - run:
          name: Push to Docker Hub
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push dynkine/docker-express-app